server:
  port: 8082

spring:
  application:
    name: user

eureka:
  client:
    service-url:
      defaultZone: http://intellitor:8761/eureka
  instance:
    preferIpAddress: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
  api-docs:
    path: /api-docs