server:
  port: 8085

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      configurations: health-check
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s
      routes:
        - id: dao
          uri: lb://dao
          port: 8081
          predicates:
            - Path=/dao/**
        - id: user
          uri: lb://user
          port: 8082
          predicates:
            - Path=/user/**
        - id: course
          uri: lb://course
          port: 8083
          predicates:
            - Path=/course/**
        - id: enrollment
          uri: lb://enrollment
          port: 8084
          predicates:
            - Path=/enrollment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true