server:
  port: 8085

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: dao
          uri: lb://DAO
          predicates:
            - Path=/dao/**
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user/**
        - id: course
          uri: lb://COURSE
          predicates:
            - Path=/course/**
        - id: enrollment
          uri: lb://ENROLLMENT
          predicates:
            - Path=/enrollment/**

eureka:
  client:
    service-url:
      defaultZone: http://intellitor:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true