server:
  port: 8085

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      configurations: health-check
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s
      routes:
        - id: dao
          uri: lb://dao
          port: 8081
          predicates:
            - Path=/**
        - id: user
          uri: lb://user
          port: 8082
          predicates:
            - Path=/**
        - id: course
          uri: lb://course
          port: 8083
          predicates:
            - Path=/**
        - id: enrollment
          uri: lb://enrollment
          port: 8084
          predicates:
            - Path=/**
eureka:
  client:
    service-url:
      defaultZone: http://intellitor:8761/eureka
    register-with-eureka: true
    fetch-registry: true